apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etherpad
  labels:
    name: etherpad
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - pad.joroeder.de
      secretName: ether-tls
  rules:
  - host: pad.joroeder.de
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: etherpad
            port: 
              number: 9001
