apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "database-%s" .Release.Name }}
type: Opaque
data:
  DB_PASS: {{ .Values.secret.DB_PASS | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.ADMIN_PASSWORD | b64enc | quote }}
  APIKEY: {{ .Values.secret.APIKEY | b64enc | quote }}