{{- if (not .Values.mailer.existingSecret)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "humhub.mailerSecretName" . }}
type: Opaque
data:
  SMTP: {{.Values.mailer.password | b64enc | quote }}
{{- end }}