{{- if (not .Values.externalDatabase.existingSecret)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "humhub.databaseSecretName" . }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}