apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HUMHUB_ADMIN_LOGIN
              value: {{.Values.adminUsername}}
            - name: HUMHUB_ADMIN_EMAIL
              value: {{.Values.adminEmail | quote }}
            - name: HUMHUB_ADMIN_PASSWORD
              value: {{.Values.adminPassword | quote }}
            - name: HUMHUB_DB_NAME
              value: {{.Values.externalDatabase.name | quote }}
            - name: HUMHUB_DB_HOST
              value: {{.Values.externalDatabase.host | quote }}
            - name: HUMHUB_DB_PORT
              value: {{.Values.externalDatabase.port | quote }}
            - name: HUMHUB_DB_PASSWORD
              value: {{ .Values.externalDatabase.password | quote }}
            - name: HUMHUB_NAME
              value: {{ .Values.humhubInstanceName | quote }}
            - name: HUMHUB_EMAIL
              value: {{ .Values.humhubEmail | quote }}
            - name: HUMHUB_LANG
              value: {{ .Values.humhubLanguage | quote }}
            - name: HUMHUB_DEBUG
              value: {{ .Values.humhubDebugMode | quote }}
            - name: HUMHUB_ANONYMOUS_REGISTRATION
              value: {{ .Values.anonymosRegistration | quote }}
            - name: HUMHUB_ALLOW_GUEST_ACCESS
              value: {{ .Values.guestAcess | quote }}
            - name: HUMHUB_NEED_APPROVAL
              value: {{ .Values.needAproval | quote }}
            - name: HUMHUB_LDAP_ENABLED
              value: {{ .Values.ldap.enabled | quote }}   
            - name: HUMHUB_LDAP_HOSTNAME
              value: {{ .Values.ldap.hostname | quote }}   
            - name: HUMHUB_LDAP_PORT
              value: {{ .Values.ldap.port | quote }}    
            - name: HUMHUB_LDAP_BASE_DN
              value: {{ .Values.ldap.baseDn | quote }}
            - name: HUMHUB_LDAP_LOGIN_FILTER
              value: {{ .Values.ldap.loginFilter | quote }}
            - name: HUMHUB_LDAP_USER_FILTER
              value: {{ .Values.ldap.userFilter | quote }}
            - name: HUMHUB_LDAP_USERNAME_ATTRIBUTE
              value: {{ .Values.ldap.usernameAttribute | quote }} 
            - name: HUMHUB_LDAP_EMAIL_ATTRIBUTE
              value: {{ .Values.ldap.emailAttribute | quote }} 
            - name: HUMHUB_LDAP_ID_ATTRIBUTE
              value: {{ .Values.ldap.idAttribute | quote }} 
            - name: HUMHUB_LDAP_REFRESH_USERS
              value: {{ .Values.ldap.refreshUsers | quote }}
            - name: HUMHUB_LDAP_CACERT
              value: {{ .Values.ldap.cacert | quote }}
            - name: HUMHUB_LDAP_SKIP_VERIFY
              value: {{ .Values.ldap.skipVerify | quote }}
            - name: PHP_POST_MAX_SIZE
              value: {{ .Values.php.postMaxSize | quote }} 
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: {{ .Values.php.uploadMaxSize | quote }} 
            - name: PHP_MAX_EXECUTION_TIME
              value: {{ .Values.php.maxExecutionTime | quote }}
            - name: PHP_MEMORY_LIMIT
              value: {{ .Values.php.memoryLimit | quote }} 
            - name: PHP_TIMEZONE
              value: {{ .Values.php.timezone | quote }} 
            - name: HUMHUB_REDIS_HOSTNAME
              value: {{ .Values.redis.hostname | quote }}
            - name: HUMHUB_REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: HUMHUB_REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
          volumeMounts:
            - name: config
              mountPath: /var/www/localhost/htdocs/protected/config
              subPath: config
            - name: uploads
              mountPath: /var/www/localhost/htdocs/uploads
              subPath: uploads
            - name: modules
              mountPath: /var/www/localhost/htdocs/protected/modules
              subPath: modules
      volumes:
        - name: uploads
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim: 
            claimName: {{ .Values.persistence.existingClaim | default "uploads" }}
          {{- else }}
            emptyDir: {}
        - name: modules
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim: 
            claimName: {{ .Values.persistence.existingClaim | default "modules" }}
          {{- else }}
            emptyDir: {}
          
          
      #{{- with .Values.nodeSelector }}
      #nodeSelector:
      #  {{- toYaml . | nindent 8 }}
      #{{- end }}
      #{{- with .Values.affinity }}
      #affinity:
      #  {{- toYaml . | nindent 8 }}
      #{{- end }}
      #{{- with .Values.tolerations }}
      #tolerations:
      #  {{- toYaml . | nindent 8 }}
      #{{- end }}